### PR TITLE
Fix Arduino IDE 2.2.1 Compilation error when using Arduino Mega 

### PR DESCRIPTION
**Pull request by sirdel**
On a fresh Arduino 2.2.1 IDE install, when using Arduino Mega in the boards manager. I get a 

```
speeduino/speeduino/board_avr2560.h:30:23: fatal error: Time.h: No such file or directory
     #define RTC_LIB_H <Time.h>

compilation terminated.

exit status 1

Compilation error: Time.h: No such file or directory
```

From v1.6.1 of Michael Margolis Time library programs should include TimeLib.h. This PR fixes this error for the latest Arduino IDE.

### CODE REVIEW

**Comment by noisymime** [comment]
I'm actually seeing the opposite here. The current code works fine, but using `TimeLib.h` results in:

```
In file included from /Users/josh/Documents/Arduino/speeduino/speeduino/globals.h:110:0,
                 from /Users/josh/Documents/Arduino/speeduino/speeduino/speeduino.ino:24:
/Users/josh/Documents/Arduino/speeduino/speeduino/board_avr2560.h:30:23: fatal error: TimeLib.h: No such file or directory
     #define RTC_LIB_H <TimeLib.h>
                       ^
compilation terminated.
Alternatives for TimeLib.h: []
ResolveLibrary(TimeLib.h)
  -> candidates: []
```

Certainly `TimeLib.h` is the more up to date library, but does it need to be manually installed through the library manager?

**Comment by sirdel** [comment]
For me (on Debian Buster), using the default internal library, it compiles if I change to lowercase T ie
`<time.h>`

Which is using :- 
 `.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/avr/include/time.h`

**Comment by adbancroft** [comment]
Keep in mind that Windows is case **in**sensitive and the default Linux file system is case sensitive.......

**Comment by noisymime** [comment]
Closing this for now as I cannot reproduce on linux or Windows.

**Pull request closed without merging**
