### PR TITLE
Suzuki k6a fix & "improvements"

### LINKED ISSUE #1173: Suzuki K6A RPM code issue (minor bug)
`getRPM_SuzukiK6A()` calls `stdGetRPM(720)`. A while back we changed the signature of `stdGetRPM` to `stdGetRPM(bool isCamTeeth)`: `getRPM_SuzukiK6A()` should probably be calling `stdGetRPM(CAM_SPEED)`

### PR DESCRIPTION
**Pull request by adbancroft**
Fixes #1173 

Plus a couple of code clean ups - all in separate commits, so cherry pick if needed.

### CODE REVIEW

**Comment by adbancroft** [comment]
@mike501 Probably worth you taking a quick look?

**Comment by noisymime** [comment]
Have these been tested on a car at all?

I'm fine with the specific bug fix of updating this to the new rpm calculate function, but there seems to be some logic changes here also around both the crank angle and the end tooth determination.

**Comment by adbancroft** [comment]
> Have these been tested on a car at all?

No - I was hoping @mike501 would comment. I did add unit tests to cover the changes - the positive test cases pass on master & the PR.

**Comment by mike501** [comment]
Sorry folks, I'm not able to do anything at the moment. I also don't have a
car to test, I wrote the code for someone else. I'll try to find them and
point them at this.

**Comment by mike501** [comment]
I've messaged user raku on discord. He's who I wrote the code for and
tested it for 300+km prior to submission.

**Pull request merged**
